project_id = "gvsssciqwzqehwjafqqr"

[functions.shopify-stock-sync]
verify_jwt = false

[functions.ai-generate-description]
verify_jwt = false

[functions.import-commit]
verify_jwt = false

[functions.ebay-auth]
verify_jwt = false

[functions.ebay-inventory]
verify_jwt = false

[functions.scrape-and-generate]
verify_jwt = false