
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS manufacturer text,
  ADD COLUMN IF NOT EXISTS country_of_origin text,
  ADD COLUMN IF NOT EXISTS ebay_category_id text,
  ADD COLUMN IF NOT EXISTS shopify_collection text,
  ADD COLUMN IF NOT EXISTS product_status text DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS ebay_listed_price numeric,
  ADD COLUMN IF NOT EXISTS shopify_listed_price numeric,
  ADD COLUMN IF NOT EXISTS tax_class text DEFAULT 'gst_included',
  ADD COLUMN IF NOT EXISTS reorder_level integer,
  ADD COLUMN IF NOT EXISTS supplier_product_code text,
  ADD COLUMN IF NOT EXISTS lead_time_days integer,
  ADD COLUMN IF NOT EXISTS length_mm integer,
  ADD COLUMN IF NOT EXISTS width_mm integer,
  ADD COLUMN IF NOT EXISTS height_mm integer,
  ADD COLUMN IF NOT EXISTS unit_of_measure text,
  ADD COLUMN IF NOT EXISTS storage_requirements text,
  ADD COLUMN IF NOT EXISTS shelf_life_notes text,
  ADD COLUMN IF NOT EXISTS artg_inclusion_type text,
  ADD COLUMN IF NOT EXISTS scheduled_drug text,
  ADD COLUMN IF NOT EXISTS pbs_listed boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS pbs_item_code text,
  ADD COLUMN IF NOT EXISTS ndss_product boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS requires_prescription boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS age_restriction text,
  ADD COLUMN IF NOT EXISTS regulatory_notes text,
  ADD COLUMN IF NOT EXISTS short_description text,
  ADD COLUMN IF NOT EXISTS full_description_html text,
  ADD COLUMN IF NOT EXISTS key_features text[],
  ADD COLUMN IF NOT EXISTS allergen_information text,
  ADD COLUMN IF NOT EXISTS upc text,
  ADD COLUMN IF NOT EXISTS gtin14 text,
  ADD COLUMN IF NOT EXISTS mpn text,
  ADD COLUMN IF NOT EXISTS supplier_barcode text,
  ADD COLUMN IF NOT EXISTS tags text[],
  ADD COLUMN IF NOT EXISTS last_modified_by text;
